# Generated by Django 5.1.6 on 2025-02-20 16:51

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_remove_task_endtime_remove_task_starttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 20, 16, 51, 50, 26585, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
