# Generated by Django 5.1.6 on 2025-02-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_task_end_time_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fixed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.CharField(choices=[('none', 'none'), ('daily', 'daily'), ('weekly', 'weekly'), ('monthly', 'monthly')], default='none', max_length=10),
            preserve_default=False,
        ),
    ]
