# Generated by Django 5.1.6 on 2025-02-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_task_fixed_task_repeat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.AlterField(
            model_name='task',
            name='repeat',
            field=models.CharField(choices=[('none', 'none'), ('daily', 'daily'), ('weekly', 'weekly')], max_length=10),
        ),
    ]
