# Generated by Django 5.1.6 on 2025-02-22 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_alter_task_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='repeat_id',
            field=models.IntegerField(default=0),
        ),
    ]
