# Generated by Django 5.1.6 on 2025-02-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_task_repeat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='repeat_id',
            field=models.IntegerField(default=0),
        ),
    ]
