# Generated by Django 5.1.6 on 2025-03-15 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_task_task_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_creator',
            new_name='user',
        ),
    ]
