# Generated by Django 5.1.6 on 2025-03-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0013_alter_task_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dueDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
