# Generated by Django 5.1.6 on 2025-03-20 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_task_duedate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='dueDate',
        ),
    ]
