# Generated by Django 5.1.6 on 2025-04-28 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0020_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='duration',
            field=models.FloatField(),
        ),
    ]
